name: On Push Run

on:
  push:
    paths:
      - '**.yml'

jobs:
  convert:
    name: Run Convert Script and push combined files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        repository: United-MC/data
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ./
      
    - name: Run Convert Script
      run: python mergeYamlAndConvert.py
      shell: sh
      
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *
        git commit -a -m "Combine files"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
